name: ESLint
on: [pull_request]
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 23
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Run eslint
        run: yarn eslint -f compact ./ --quiet
        env:
          CI: true
